# Generated by Django 3.2.7 on 2021-09-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_assets_assests_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterUniqueTogether(
            name='possesion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='possesion',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='possesion',
            name='product',
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Possesion',
        ),
    ]
