# Generated by Django 3.2.7 on 2021-09-02 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_auto_20210903_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('FN', 'Finance'), ('HR', 'Human Resources')], max_length=2)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('n', 'NonBinary'), ('u', 'Undisclosed')], max_length=1)),
            ],
        ),
    ]
