# Generated by Django 3.2.7 on 2021-09-02 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210903_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assets',
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
