# Generated by Django 3.2.7 on 2021-09-02 21:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210903_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('totalstock', models.IntegerField(blank=True, null=True)),
                ('onhand', models.IntegerField(blank=True, null=True)),
                ('minimumrequired', models.IntegerField(blank=True, null=True)),
                ('faulty', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(16, 'Employee too young!'), django.core.validators.MaxValueValidator(75, 'Employee too old!')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.EmailValidator('Invalid Email ID!')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('FN', 'Finance'), ('HR', 'Human Resources')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('n', 'NonBinary'), ('u', 'Undisclosed')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Possesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateTimeField(blank=True)),
                ('issueraised', models.BooleanField(default=False)),
                ('underprocess', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.assets')),
            ],
            options={
                'unique_together': {('employee', 'product')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='assets',
            field=models.ManyToManyField(through='main.Possesion', to='main.Assets'),
        ),
    ]
