# Generated by Django 3.2.7 on 2021-09-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='Images/avatar.png', upload_to='Images'),
        ),
    ]
